spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: 1
      value-serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
      properties:
        "[schema.registry.url]": http://localhost:8081
    consumer:
      group-id: courier-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer
      properties:
        "[schema.registry.url]": http://localhost:8081
    listener:
      concurrency: 3
server:
  port: 8085
kafka:
  topic:
    to-produce-to: notification
    to-consume-from: notification