pipeline {
    agent any
    parameters {
        choice choices: [
            'Maven',
            'Gradle'
        ], 
        description: 'Choose build tool',
        name: 'BUILD_TOOL'
    }
    // properties {
    //     promotions {
    //         promotion {
    //             name('QA')
    //             conditions {
    //                 selfPromotion(false)
    //             }
    //         }
    //         promotion {
    //             name('Prod')
    //             conditions {
    //                 manual('norbi')
    //             }
    //         }
    //     }
    // }
    stages {
        stage('Build') {
            steps {
                script {
                    currentBuild.displayName = "${params.BUILD_TOOL} #${BUILD_NUMBER}"
                    if (params.BUILD_TOOL == 'Maven') {
                        sh 'mvn -B -DskipTests clean package'
                    } else {
                        sh './gradlew clean build'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    if (params.BUILD_TOOL == 'Maven') { 
                        sh 'mvn test'
                    } else {
                        sh './gradlew test'
                    }
                }
            }
        }
        stage('Create-Artifact') {
            steps {
                script {
                    if (params.BUILD_TOOL == 'Maven') {
                        fileOperations([fileRenameOperation(
                            destination: "/var/lib/jenkins/workspace/release/admin/target/artifact${BUILD_NUMBER}.jar",
                            source: '/var/lib/jenkins/workspace/release/admin/target/admin-1.0-jar-with-dependencies.jar'
                        )])
                    } else {
                        fileOperations([fileRenameOperation(
                            destination: "/var/lib/jenkins/workspace/release/admin/build/libs/artifact${BUILD_NUMBER}.jar",
                            source: '/var/lib/jenkins/workspace/release/admin/build/libs/fat-1.0.0.jar'
                        )])
                    }
                }
            }
        }
    }
    post {
        always {
            script {
                def artifactPath = ''
                if (params.BUILD_TOOL == 'Maven') { 
                    artifactPath = "admin/target/artifact${BUILD_NUMBER}.jar"
                } else {
                    artifactPath = "admin/build/libs/artifact${BUILD_NUMBER}.jar"
                }
                archiveArtifacts artifacts: artifactPath,
                fingerprint: true,
                followSymlinks: false,
                onlyIfSuccessful: true
            }
            sh 'rm -r *'
        }
    }
}
