apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service-helm
spec:
  selector:
    app: spring-petclinic-app-helm
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001