apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic-app
  template:
    metadata:
      labels:
        app: spring-petclinic-app
    spec:
      containers:
      - name: spring-petclinic-app
        image: spring-petclinic:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: mnt
            mountPath: /home/newuser/config/application.properties
            subPath: application.properties
      volumes:
        - name: mnt
          configMap:
            name: spring-petclinic-config
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
spec:
  selector:
    app: spring-petclinic-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
