---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic-app
  template:
    metadata:
      labels:
        app: spring-petclinic-app
    spec:
      containers:
        - name: spring-petclinic-app
          image: minikube:spring-petclinic
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
spec:
  selector:
    app: spring-petclinic-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
